### ISSUE TITLE
Self-hosting

### ISSUE THREAD

**Issue by orangebutblue** [datopian/obsidian-flowershow#16]
Is it possible to use this self-hosted without something like Vercel?

**Comment by rufuspollock** [comment]
@orangebutblue yes, absolutely - you are guided through this step-by-step in the plugin. Also see step by step instructions on https://flowershow.app/#self-publish

**Comment by orangebutblue** [comment]
> @orangebutblue yes, absolutely - you are guided through this step-by-step in the plugin. Also see step by step instructions on https://flowershow.app/#self-publish

But the self-publish guide talks about using a github and a vercel account. That's what made me create this issue to begin with. Isn't it possible to publish it without relying on 3rd party cloud services?

**Comment by rufuspollock** [comment]
@orangebutblue ah ok. Do you mean:

- A) as a user without seeing / having to interact with third party cloud providers? (after all, somewhere in the background there is a cloud provider probably ...)
- B) just pushing to your own static storage 

On (A) we are working to release a Flowershow Cloud version very soon that will do what i think you want.

**Comment by rufuspollock** [comment]
@orangebutblue ok, that's completely supported - we just use  vercel as an example. You can just run this locally

```
npm run build && npm run export
```

And then take the `out` folder and push it anywhere you want! 😄
